name: Greetings

on:
  issues:
  push:
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! We are so happy to see you here! Make sure to follow the Issue Template!'
        pr-message: 'Hi! We are so happy to see you here! First, choose a label for your PR according to your changes (minor, major, patch).'
