# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.8.6', '3.9.8', '3.10.0']
        os: [ubuntu-18.04, ubuntu-latest, windows-2022, windows-latest, macos-11, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
      - run: pipenv install
      # Runs a set of commands using the runners shell
      - name: Test
        run: |
          cd src/ && python3 -m unittest discover tests
