name: Update Checksums

on:
  - push
  - workflow_dispatch
  
jobs:
  write_sums:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: write checksums
        run: |
          find . -type f -not -path "./.git/*" -not -path "./scripts/checksums.txt" -exec sha256sum {} \; > ./scripts/checksums.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[norelease] Update checksums."
          git push
